"use client";
import { useMemo, useState } from "react";

export default function OsefBotKnowledgeManager({ connaissances: initiales }) {
  const [items,setItems]=useState(initiales); const [q,setQ]=useState(""); const [edit,setEdit]=useState(null); const [msg,setMsg]=useState("");
  const visibles=useMemo(()=>items.filter(k=>[k.questionReference,k.reponse,...(k.formulations||[])].join(" ").toLowerCase().includes(q.toLowerCase())),[items,q]);
  async function action(id, method, body) {
    setMsg(""); const r=await fetch("/api/admin/osefbot/knowledge/"+id,{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined}); const d=await r.json();
    if(!r.ok){setMsg(d.error||"Erreur");return false} return true;
  }
  async function sauver(){ if(!edit) return; const body={...edit,formulations:typeof edit.formulations==="string"?edit.formulations.split("\n").map(x=>x.trim()).filter(Boolean):edit.formulations}; if(await action(edit.id,"PATCH",body)){setItems(x=>x.map(k=>k.id===edit.id?{...k,...body,formulations:body.formulations}:k));setEdit(null);setMsg("Connaissance mise à jour ✓");}}
  async function basculer(k){if(await action(k.id,"PATCH",{actif:!k.actif})){setItems(x=>x.map(i=>i.id===k.id?{...i,actif:!i.actif}:i));}}
  async function supprimer(k){if(!confirm("Supprimer définitivement cette connaissance d’OSEFBOT ?"))return;if(await action(k.id,"DELETE"))setItems(x=>x.filter(i=>i.id!==k.id));}
  return <section className="space-y-3">
    <div><h2 className="text-xl font-bold text-brand-dark">Connaissances OSEFBOT</h2><p className="text-sm text-brand-dark/50">Gère les réponses que tu as apprises au bot.</p></div>
    <div className="rounded-2xl border border-black/5 bg-white p-4 dark:border-white/10 dark:bg-brand-night"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Rechercher dans sa mémoire…" className="w-full rounded-xl border border-black/10 bg-transparent px-4 py-2.5 text-sm dark:border-white/10"/><p className="mt-2 text-xs text-brand-dark/40">{visibles.length} connaissance(s), dont {items.filter(x=>x.actif).length} active(s)</p></div>
    {msg&&<p className="rounded-xl bg-brand-green/10 p-3 text-sm font-semibold text-brand-dark">{msg}</p>}
    <div className="grid gap-3">{visibles.map(k=><article key={k.id} className="rounded-2xl border border-black/5 bg-white p-4 dark:border-white/10 dark:bg-brand-night">
      <div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex gap-2"><span className={`rounded-full px-2 py-1 text-[11px] font-bold ${k.actif?"bg-brand-green/15 text-brand-greendark":"bg-black/5 text-brand-dark/45 dark:bg-white/10"}`}>{k.actif?"Active":"Désactivée"}</span><span className="text-xs text-brand-dark/35">Maj {k.updatedAt}</span></div><p className="mt-3 font-bold text-brand-dark">{k.questionReference}</p><p className="mt-1 text-sm text-brand-dark/65">{k.reponse}</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-brand-dark/45"><span>{k.formulations?.length||0} formulation(s) similaire(s)</span><span>{k.nombreUtilisations||0} utilisation(s)</span><span>{k.derniereUtilisation ? `Dernière : ${k.derniereUtilisation}` : "Jamais utilisée"}</span><span>👍 {k.avisPositifs||0}</span><span>👎 {k.avisNegatifs||0}</span><span>{(k.avisPositifs||0)+(k.avisNegatifs||0)>0 ? `${Math.round(((k.avisPositifs||0)/((k.avisPositifs||0)+(k.avisNegatifs||0)))*100)} % utiles` : "Pas encore évaluée"}</span></div>{k.actionHref&&<p className="mt-1 text-xs font-semibold text-brand-greendark">→ {k.actionLabel} · {k.actionHref}</p>}</div>
      <div className="flex flex-wrap gap-2"><button onClick={()=>setEdit({...k,formulations:(k.formulations||[]).join("\n")})} className="rounded-lg bg-black/5 px-3 py-2 text-xs font-semibold dark:bg-white/10">Modifier</button><button onClick={()=>basculer(k)} className="rounded-lg bg-brand-yellow/20 px-3 py-2 text-xs font-semibold">{k.actif?"Désactiver":"Activer"}</button><button onClick={()=>supprimer(k)} className="rounded-lg bg-red-500/10 px-3 py-2 text-xs font-semibold text-red-600">Supprimer</button></div></div>
      {edit?.id===k.id&&<div className="mt-4 space-y-2 border-t border-black/5 pt-4 dark:border-white/10"><input value={edit.questionReference} onChange={e=>setEdit({...edit,questionReference:e.target.value})} className="w-full rounded-xl border border-black/10 bg-transparent px-3 py-2 text-sm dark:border-white/10"/><textarea rows={4} value={edit.reponse} onChange={e=>setEdit({...edit,reponse:e.target.value})} className="w-full rounded-xl border border-black/10 bg-transparent px-3 py-2 text-sm dark:border-white/10"/><textarea rows={3} value={edit.formulations} onChange={e=>setEdit({...edit,formulations:e.target.value})} className="w-full rounded-xl border border-black/10 bg-transparent px-3 py-2 text-sm dark:border-white/10" placeholder="Une formulation par ligne"/><div className="grid gap-2 sm:grid-cols-2"><input value={edit.actionLabel||""} onChange={e=>setEdit({...edit,actionLabel:e.target.value})} className="rounded-xl border border-black/10 bg-transparent px-3 py-2 text-sm dark:border-white/10" placeholder="Texte du bouton"/><input value={edit.actionHref||""} onChange={e=>setEdit({...edit,actionHref:e.target.value})} className="rounded-xl border border-black/10 bg-transparent px-3 py-2 text-sm dark:border-white/10" placeholder="/destination"/></div><div className="flex gap-2"><button onClick={sauver} className="rounded-xl bg-brand-green px-4 py-2 text-xs font-bold text-[#16231A]">Enregistrer</button><button onClick={()=>setEdit(null)} className="rounded-xl bg-black/5 px-4 py-2 text-xs dark:bg-white/10">Annuler</button></div></div>}
    </article>)}</div>
  </section>;
}
